# TODO: need containers for at least serwer, backend and frontend?. Prob smth for queues (rabbit?) and a DB? maybe? 
# also a network to connect all of these
# does frontend even need anything special?